name: Process Addresses

on:
  schedule:
    - cron: '0 0 * * *'  # This will run the workflow every day at midnight
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install pyyaml requests

    - name: Download data file
      run: python .github/scripts/download_file.py

    - name: Process addresses
      run: python .github/scripts/process_addresses.py

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add ipv4.txt ipv6.txt
        git commit -m "Automatically separate IPv4 and IPv6 addresses"
        git push https://${{ secrets.GH_PAT }}@github.com/CalebChen768/cn_ipv4_ipv6.git
